# Generated by Django 5.1.7 on 2025-03-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='parent_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='parent',
            name='parent_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='parent',
            name='parent_phone',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='parent',
            name='parent_picture',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='students',
            name='student_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='students',
            name='student_dob',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='students',
            name='student_picture',
            field=models.CharField(default='', max_length=255),
        ),
    ]
