# Generated by Django 5.1.7 on 2025-03-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_parent_parent_address_parent_parent_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='student_gender',
            field=models.CharField(default='', max_length=255),
        ),
    ]
