# Generated by Django 5.1.7 on 2025-03-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_students_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='student_picture',
            field=models.ImageField(default='default.jpg', upload_to='student_pictures/'),
        ),
    ]
