# Generated by Django 5.1.7 on 2025-03-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_alter_students_student_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='student_picture',
            field=models.ImageField(default='student_pictures/default.jpg', upload_to='student_pictures/'),
        ),
    ]
