# Generated by Django 5.1.7 on 2025-03-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_alter_students_student_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_dob',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_gender',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_picture',
            field=models.ImageField(default='teacher_pictures/default.jpg', upload_to='teacher_pictures/'),
        ),
    ]
