# Generated by Django 5.1.7 on 2025-03-26 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_teacher_teacher_address_teacher_teacher_dob_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assign_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.section')),
                ('assign_steacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.teacher')),
            ],
        ),
    ]
