# Generated by Django 5.1.7 on 2025-03-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_assign_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='parent_picture',
            field=models.ImageField(default='parent_pictures/default.jpg', upload_to='parent_pictures/'),
        ),
    ]
