# Generated by Django 5.1.7 on 2025-04-06 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_alter_parent_parent_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_content', models.TextField()),
                ('notification_date', models.DateTimeField(auto_now_add=True)),
                ('notification_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_class', to='administrator.class')),
            ],
        ),
    ]
