# Generated by Django 5.1.7 on 2025-04-06 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='notification_subject',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='administrator.subject'),
        ),
    ]
