# Generated by Django 5.1.7 on 2025-04-06 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0010_notifications_notification_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='notification_subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administrator.subject'),
        ),
    ]
