# Generated by Django 5.1.7 on 2025-04-06 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0011_alter_notifications_notification_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='notification_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_subject', to='administrator.subject'),
        ),
    ]
