# Generated by Django 5.1.7 on 2025-04-08 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0012_alter_notifications_notification_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_date', models.DateTimeField(auto_now_add=True)),
                ('assignment_instruction', models.TextField()),
                ('assignment_material', models.FileField(upload_to='assignments_materials/')),
                ('assignment_deadline', models.CharField(max_length=255)),
                ('assignment_sta', models.BooleanField(default=True)),
                ('assignment_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_class', to='administrator.class')),
                ('assignment_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_subject', to='administrator.subject')),
            ],
        ),
    ]
