# Generated by Django 5.1.7 on 2025-04-08 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0013_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment_submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_assignment', to='administrator.assignment')),
            ],
        ),
    ]
