# Generated by Django 5.1.7 on 2025-04-08 20:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0014_assignment_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment_submission',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment_submission',
            name='submission_material',
            field=models.FileField(default='assignments_submission_materials/letter_head', upload_to='assignments_submission_materials/'),
        ),
        migrations.AddField(
            model_name='assignment_submission',
            name='submission_student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='submission_student', to='administrator.students'),
            preserve_default=False,
        ),
    ]
