# Generated by Django 5.1.7 on 2025-04-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0015_assignment_submission_submission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment_submission',
            name='submission_material',
            field=models.FileField(upload_to='assignments_submission_materials/'),
        ),
    ]
