# Generated by Django 5.1.7 on 2025-04-08 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0016_alter_assignment_submission_submission_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_submission_date', models.DateTimeField(auto_now_add=True)),
                ('question_material', models.FileField(upload_to='question_papers/')),
                ('question_sta', models.BooleanField(default=False)),
                ('question_approve_date', models.CharField(default='-', max_length=255)),
                ('question_approve_comment', models.TextField(default='-')),
                ('question_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_class', to='administrator.class')),
                ('question_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_subject', to='administrator.subject')),
                ('question_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_teacher', to='administrator.teacher')),
            ],
        ),
    ]
