# Generated by Django 5.1.7 on 2025-04-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0017_exam_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_name', models.CharField(max_length=255)),
                ('term_sta', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='exam_questions',
            name='question_term',
            field=models.CharField(default='', max_length=255),
        ),
    ]
