# Generated by Django 5.1.7 on 2025-04-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0018_session_term_exam_questions_question_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_questions',
            name='question_session',
            field=models.CharField(default='', max_length=255),
        ),
    ]
