# Generated by Django 5.1.7 on 2025-04-12 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0021_alter_grade_grade_ca_alter_grade_grade_exam_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_term', models.CharField(max_length=255)),
                ('payment_session', models.CharField(max_length=255)),
                ('payment_description', models.TextField()),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_amount', models.CharField(max_length=255)),
                ('payment_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_student', to='administrator.students')),
            ],
        ),
    ]
