# Generated by Django 5.1.7 on 2025-04-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0022_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_term', models.CharField(max_length=255)),
                ('event_session', models.CharField(max_length=255)),
                ('event_date', models.CharField(max_length=255)),
            ],
        ),
    ]
