# Generated by Django 5.1.7 on 2025-04-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0023_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='General_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_not_audience', models.CharField(max_length=255)),
                ('g_not_date', models.DateTimeField(auto_now_add=True)),
                ('g_not_notification', models.TextField()),
            ],
        ),
    ]
