# Generated by Django 5.1.7 on 2025-04-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0024_general_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='general_notification',
            name='g_not_session',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='general_notification',
            name='g_not_term',
            field=models.CharField(default='', max_length=255),
        ),
    ]
