# Generated by Django 5.1.7 on 2025-04-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0025_general_notification_g_not_session_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=255)),
                ('blog_date', models.DateTimeField(auto_now_add=True)),
                ('blog_content', models.TextField()),
                ('blog_cover', models.ImageField(upload_to='blog_pictures/')),
            ],
        ),
    ]
