# Generated by Django 5.1.7 on 2025-04-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0027_blog_blog_sta'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_session',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_term',
            field=models.CharField(default='', max_length=255),
        ),
    ]
