# Generated by Django 5.1.7 on 2025-04-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0028_blog_blog_session_blog_blog_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_cover', models.ImageField(upload_to='gallery/')),
                ('gallery_sta', models.BooleanField(default=False)),
            ],
        ),
    ]
