# Generated by Django 5.1.7 on 2025-04-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0029_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment_submission',
            name='submission_cumment',
            field=models.TextField(default=''),
        ),
    ]
