# Generated by Django 5.1.7 on 2025-04-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0030_assignment_submission_submission_cumment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment_submission',
            name='submission_cumment',
            field=models.TextField(default='-'),
        ),
    ]
