# Generated by Django 5.1.7 on 2025-04-15 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0031_alter_assignment_submission_submission_cumment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment_submission',
            old_name='submission_cumment',
            new_name='submission_comment',
        ),
    ]
